apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: og2zgzmry-go 
  janus-idp.io/tekton: og2zgzmry-go
  backstage.io/kubernetes-id: og2zgzmry-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: og2zgzmry-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml