apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: og2zgzmry-go
  janus-idp.io/tekton: og2zgzmry-go
  backstage.io/kubernetes-id: og2zgzmry-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: og2zgzmry-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
